import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/common/styles/globals.css";
import "@/common/styles/index.scss";
import { ReduxProviders } from "@/common/redux/provider";
import Providers from "@/common/utils/provider";
import Head from "next/head";
import Script from "next/script";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            {/* <Head>
                <Script
                    dangerouslySetInnerHTML={{
                        __html: `
              window.fbAsyncInit = function() {
                 FB.init({
                   appId      : '374799038280633',
                   xfbml      : true,
                   version    : 'v18.0'
                 });
                 FB.AppEvents.logPageView();
                 FB.getLoginStatus(function(response) {
                    console.log(response);
                    statusChangeCallback(response);
                  });
               };
             
               (function(d, s, id){
                  var js, fjs = d.getElementsByTagName(s)[0];
                  if (d.getElementById(id)) {return;}
                  js = d.createElement(s); js.id = id;
                  js.src = "https://connect.facebook.net/en_US/sdk.js";
                  fjs.parentNode.insertBefore(js, fjs);
                }(document, 'script', 'facebook-jssdk'));
             
             `,
                    }}
                />
            </Head> */}
            <body className={inter.className}>
                {" "}
                <ReduxProviders>
                    <Providers>{children}</Providers>
                </ReduxProviders>
            </body>
        </html>
    );
}
